[package]
name = "jute"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "dylib", "staticlib"]

[dependencies]
bytes = "1.6.0"
indexmap = "2.2.6"
maplit = "1.0.2"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
